# Site settings
title: The Player Project
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Player Project develops and maintains open-source robotics software
  for roboticists worldwide.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://playerproject.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  playerproject

# Build settings
markdown: kramdown
